import type { Temple } from '@/types/temple';

/**
 * Curated list of famous Jain temples across India and worldwide.
 * Used as a seed dataset until we wire up a backend proxy for Google Places API.
 *
 * Coordinates are approximate but accurate enough to render correctly on a map.
 * All major pilgrimage sites (tirthas) and city temples are represented.
 */
export const SEED_TEMPLES: Temple[] = [
  // ─── DELHI ─────────────────────────────────────────────────
  {
    placeId: 'seed-delhi-lal-mandir',
    name: 'Shri Digambar Jain Lal Mandir',
    address: 'Chandni Chowk, Old Delhi',
    location: { latitude: 28.6562, longitude: 77.2334 },
    sampradaya: 'digambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-delhi-naya-mandir',
    name: 'Naya Mandir (Padampura Mandir)',
    address: 'Dharampura, Old Delhi',
    location: { latitude: 28.6502, longitude: 77.2330 },
    sampradaya: 'digambar',
    rating: 4.5,
  },
  {
    placeId: 'seed-delhi-atma-vallabh',
    name: 'Shri Atma Vallabh Jain Smarak',
    address: 'GT Karnal Road, Alipur, Delhi',
    location: { latitude: 28.7935, longitude: 77.1525 },
    sampradaya: 'shvetambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-delhi-ahinsa-sthal',
    name: 'Ahinsa Sthal',
    address: 'Mehrauli, New Delhi',
    location: { latitude: 28.5244, longitude: 77.1855 },
    sampradaya: 'digambar',
    rating: 4.5,
  },
  {
    placeId: 'seed-delhi-kund-kund-bharti',
    name: 'Kund Kund Bharti',
    address: 'Bhagwan Mahaveer Marg, Delhi',
    location: { latitude: 28.5497, longitude: 77.2090 },
    sampradaya: 'digambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-delhi-parshwanath-naraina',
    name: 'Shri Parshwanath Digambar Jain Mandir',
    address: 'Naraina, New Delhi',
    location: { latitude: 28.6357, longitude: 77.1391 },
    sampradaya: 'digambar',
    rating: 4.5,
  },

  // ─── MUMBAI ────────────────────────────────────────────────
  {
    placeId: 'seed-mumbai-walkeshwar',
    name: 'Babu Amichand Panalal Adishwarji Jain Temple',
    address: 'Walkeshwar, Mumbai',
    location: { latitude: 18.9540, longitude: 72.7956 },
    sampradaya: 'shvetambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-mumbai-godiji',
    name: 'Godiji Parshwanath Jain Temple',
    address: 'Pydhonie, Mumbai',
    location: { latitude: 18.9510, longitude: 72.8240 },
    sampradaya: 'shvetambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-mumbai-mahavir-dadar',
    name: 'Shri Mahavir Swami Jain Derasar',
    address: 'Dadar, Mumbai',
    location: { latitude: 19.0186, longitude: 72.8425 },
    sampradaya: 'shvetambar',
    rating: 4.5,
  },
  {
    placeId: 'seed-mumbai-ghatkopar',
    name: 'Shri Adishwar Jain Temple',
    address: 'Ghatkopar, Mumbai',
    location: { latitude: 19.0857, longitude: 72.9081 },
    sampradaya: 'shvetambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-mumbai-mulund',
    name: 'Shri Shantinath Jain Temple',
    address: 'Mulund, Mumbai',
    location: { latitude: 19.1726, longitude: 72.9400 },
    sampradaya: 'shvetambar',
    rating: 4.5,
  },
  {
    placeId: 'seed-mumbai-borivali',
    name: 'Shri Vasupujya Jain Derasar',
    address: 'Borivali West, Mumbai',
    location: { latitude: 19.2307, longitude: 72.8567 },
    sampradaya: 'shvetambar',
    rating: 4.4,
  },

  // ─── KOLKATA ───────────────────────────────────────────────
  {
    placeId: 'seed-kolkata-pareshnath',
    name: 'Pareshnath Jain Temple (Badridas)',
    address: 'Maniktala, Kolkata',
    location: { latitude: 22.5972, longitude: 88.3855 },
    sampradaya: 'shvetambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-kolkata-shitalnath',
    name: 'Shitalnath Ji Mandir',
    address: 'Maniktala, Kolkata',
    location: { latitude: 22.5980, longitude: 88.3860 },
    sampradaya: 'shvetambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-kolkata-chandraprabhuji',
    name: 'Chandraprabhuji Mandir',
    address: 'Maniktala, Kolkata',
    location: { latitude: 22.5975, longitude: 88.3858 },
    sampradaya: 'shvetambar',
    rating: 4.5,
  },
  {
    placeId: 'seed-kolkata-belgachia',
    name: 'Mahavir Swami Jain Mandir',
    address: 'Belgachia, Kolkata',
    location: { latitude: 22.6128, longitude: 88.3900 },
    sampradaya: 'digambar',
    rating: 4.4,
  },

  // ─── RAJASTHAN ─────────────────────────────────────────────
  {
    placeId: 'seed-raj-dilwara',
    name: 'Dilwara Jain Temples',
    address: 'Mount Abu, Sirohi District',
    location: { latitude: 24.6116, longitude: 72.7244 },
    sampradaya: 'shvetambar',
    rating: 4.8,
  },
  {
    placeId: 'seed-raj-ranakpur',
    name: 'Ranakpur Chaturmukha Jain Temple',
    address: 'Ranakpur, Pali',
    location: { latitude: 25.1167, longitude: 73.4717 },
    sampradaya: 'shvetambar',
    rating: 4.8,
  },
  {
    placeId: 'seed-raj-nakoda',
    name: 'Shri Nakoda Jain Tirth',
    address: 'Mewanagar, Barmer',
    location: { latitude: 25.9166, longitude: 72.3583 },
    sampradaya: 'shvetambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-raj-mahavirji',
    name: 'Shri Mahavir Ji Atishay Kshetra',
    address: 'Sawai Madhopur',
    location: { latitude: 26.7891, longitude: 76.6422 },
    sampradaya: 'digambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-raj-padampura',
    name: 'Padampura Atishay Kshetra',
    address: 'Bassi, Jaipur',
    location: { latitude: 27.0238, longitude: 75.6428 },
    sampradaya: 'digambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-raj-soniji-nasiyan',
    name: 'Soniji Ki Nasiyan (Red Temple)',
    address: 'Ajmer',
    location: { latitude: 26.4582, longitude: 74.6391 },
    sampradaya: 'digambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-raj-jaisalmer-fort',
    name: 'Jain Temples of Jaisalmer Fort',
    address: 'Jaisalmer Fort',
    location: { latitude: 26.9117, longitude: 70.9118 },
    sampradaya: 'shvetambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-raj-lodhrva',
    name: 'Lodhrva Jain Temple',
    address: 'Lodhrva, Jaisalmer',
    location: { latitude: 27.0000, longitude: 70.7833 },
    sampradaya: 'shvetambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-raj-bhandasar',
    name: 'Bhandasar Jain Temple',
    address: 'Bikaner',
    location: { latitude: 28.0150, longitude: 73.3122 },
    sampradaya: 'shvetambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-raj-osian',
    name: 'Osian Mahavira Jain Temple',
    address: 'Osian, Jodhpur',
    location: { latitude: 26.7300, longitude: 72.9100 },
    sampradaya: 'shvetambar',
    rating: 4.5,
  },
  {
    placeId: 'seed-raj-jaipur-sanghiji',
    name: 'Sanghiji Jain Mandir',
    address: 'Sanganer, Jaipur',
    location: { latitude: 26.8189, longitude: 75.7894 },
    sampradaya: 'digambar',
    rating: 4.6,
  },

  // ─── GUJARAT ───────────────────────────────────────────────
  {
    placeId: 'seed-guj-palitana',
    name: 'Shatrunjaya Jain Temples (Palitana)',
    address: 'Palitana, Bhavnagar',
    location: { latitude: 21.4860, longitude: 71.7766 },
    sampradaya: 'shvetambar',
    rating: 4.9,
  },
  {
    placeId: 'seed-guj-girnar',
    name: 'Girnar Jain Temples',
    address: 'Girnar, Junagadh',
    location: { latitude: 21.5117, longitude: 70.5125 },
    sampradaya: 'shvetambar',
    rating: 4.8,
  },
  {
    placeId: 'seed-guj-taranga',
    name: 'Taranga Jain Temple',
    address: 'Taranga Hill, Mehsana',
    location: { latitude: 24.2500, longitude: 72.7500 },
    sampradaya: 'shvetambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-guj-kumbharia',
    name: 'Kumbharia Jain Temples',
    address: 'Kumbharia, Banaskantha',
    location: { latitude: 24.2853, longitude: 72.7536 },
    sampradaya: 'shvetambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-guj-hutheesing',
    name: 'Hutheesing Jain Temple',
    address: 'Shahibaug, Ahmedabad',
    location: { latitude: 23.0379, longitude: 72.5878 },
    sampradaya: 'shvetambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-guj-shankheshwar',
    name: 'Shri Shankheshwar Parshwanath Jain Tirth',
    address: 'Shankheshwar, Patan',
    location: { latitude: 23.5167, longitude: 71.7833 },
    sampradaya: 'shvetambar',
    rating: 4.8,
  },
  {
    placeId: 'seed-guj-bhadreshwar',
    name: 'Shri Vasai Bhadreshwar Jain Tirth',
    address: 'Bhadreshwar, Kutch',
    location: { latitude: 22.9333, longitude: 69.6500 },
    sampradaya: 'shvetambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-guj-pavagadh',
    name: 'Pavagadh Jain Temples',
    address: 'Pavagadh Hill, Panchmahal',
    location: { latitude: 22.4615, longitude: 73.5378 },
    sampradaya: 'digambar',
    rating: 4.5,
  },
  {
    placeId: 'seed-guj-idar',
    name: 'Idar Jain Temple',
    address: 'Idar, Sabarkantha',
    location: { latitude: 23.8333, longitude: 73.0000 },
    sampradaya: 'shvetambar',
    rating: 4.5,
  },
  {
    placeId: 'seed-guj-mahudi',
    name: 'Mahudi Jain Temple (Ghantakarna Mahavira)',
    address: 'Mahudi, Gandhinagar',
    location: { latitude: 23.5167, longitude: 72.7167 },
    sampradaya: 'shvetambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-guj-kavi-kamboi',
    name: 'Kavi Kamboi Jain Tirth',
    address: 'Kavi Kamboi, Bharuch',
    location: { latitude: 22.0667, longitude: 72.7500 },
    sampradaya: 'shvetambar',
    rating: 4.6,
  },

  // ─── MADHYA PRADESH ────────────────────────────────────────
  {
    placeId: 'seed-mp-sonagiri',
    name: 'Sonagiri Digambar Jain Siddha Kshetra',
    address: 'Sonagiri, Datia',
    location: { latitude: 25.6166, longitude: 78.4500 },
    sampradaya: 'digambar',
    rating: 4.8,
  },
  {
    placeId: 'seed-mp-khajuraho',
    name: 'Khajuraho Jain Temple Group',
    address: 'Khajuraho, Chhatarpur',
    location: { latitude: 24.8543, longitude: 79.9258 },
    sampradaya: 'digambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-mp-bawangaja',
    name: 'Bawangaja (Adinath 84-ft Statue)',
    address: 'Barwani',
    location: { latitude: 21.9667, longitude: 75.0333 },
    sampradaya: 'digambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-mp-muktagiri',
    name: 'Muktagiri Siddha Kshetra',
    address: 'Muktagiri, Betul',
    location: { latitude: 21.4500, longitude: 77.7500 },
    sampradaya: 'digambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-mp-kundalpur',
    name: 'Kundalpur Atishay Kshetra',
    address: 'Damoh',
    location: { latitude: 23.7667, longitude: 79.4167 },
    sampradaya: 'digambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-mp-pisanhari',
    name: 'Pisanhari Madiya Jain Temple',
    address: 'Jabalpur',
    location: { latitude: 23.1700, longitude: 79.9300 },
    sampradaya: 'digambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-mp-thubonji',
    name: 'Thubonji Siddha Kshetra',
    address: 'Sagar',
    location: { latitude: 23.6500, longitude: 79.0833 },
    sampradaya: 'digambar',
    rating: 4.6,
  },

  // ─── KARNATAKA ─────────────────────────────────────────────
  {
    placeId: 'seed-kar-shravanabelagola',
    name: 'Shravanabelagola (Gomateshwara)',
    address: 'Shravanabelagola, Hassan',
    location: { latitude: 12.8587, longitude: 76.4848 },
    sampradaya: 'digambar',
    rating: 4.9,
  },
  {
    placeId: 'seed-kar-karkala',
    name: 'Karkala Gomateshwara',
    address: 'Karkala, Udupi',
    location: { latitude: 13.2167, longitude: 74.9833 },
    sampradaya: 'digambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-kar-moodbidri',
    name: 'Saavira Kambada Basadi (1000 Pillars)',
    address: 'Moodbidri, Mangalore',
    location: { latitude: 13.0667, longitude: 74.9833 },
    sampradaya: 'digambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-kar-venur',
    name: 'Venur Gomateshwara',
    address: 'Venur, Belthangady',
    location: { latitude: 12.9000, longitude: 75.0000 },
    sampradaya: 'digambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-kar-halebidu',
    name: 'Halebidu Jain Basadis',
    address: 'Halebidu, Hassan',
    location: { latitude: 13.2167, longitude: 75.9942 },
    sampradaya: 'digambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-kar-hombuja',
    name: 'Humcha (Hombuja) Jain Math',
    address: 'Humcha, Shimoga',
    location: { latitude: 13.7500, longitude: 75.2000 },
    sampradaya: 'digambar',
    rating: 4.7,
  },
  // ─── BANGALORE (detailed) ──────────────────────────────
  {
    placeId: 'seed-blr-parshwanath-chickpet',
    name: 'Shri 1008 Parshwanath Digambar Jain Mandir',
    address: 'Chickpet, Bangalore',
    location: { latitude: 12.9676, longitude: 77.5773 },
    sampradaya: 'digambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-blr-adinath-jayanagar',
    name: 'Shri 1008 Adinath Digambar Jain Mandir',
    address: 'Jayanagar 4th Block, Bangalore',
    location: { latitude: 12.9250, longitude: 77.5938 },
    sampradaya: 'digambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-blr-vasupujya-jpnagar',
    name: 'Shri Vasupujya Swami Digambar Jain Mandir',
    address: 'JP Nagar, Bangalore',
    location: { latitude: 12.9077, longitude: 77.5851 },
    sampradaya: 'digambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-blr-shankheshwar-basavanagudi',
    name: 'Shri Shankheshwar Parshwanath Jain Derasar',
    address: 'Basavanagudi, Bangalore',
    location: { latitude: 12.9416, longitude: 77.5712 },
    sampradaya: 'shvetambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-blr-mahavir-malleshwaram',
    name: 'Shri Mahavir Swami Shwetambar Jain Derasar',
    address: 'Malleshwaram, Bangalore',
    location: { latitude: 12.9939, longitude: 77.5694 },
    sampradaya: 'shvetambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-blr-adinath-sanjaynagar',
    name: 'Shri 1008 Adinath Digambar Jain Mandir',
    address: 'Sanjaynagar, Bangalore',
    location: { latitude: 13.0354, longitude: 77.5712 },
    sampradaya: 'digambar',
    rating: 4.5,
  },
  {
    placeId: 'seed-blr-adishwar-indiranagar',
    name: 'Shri Adishwar Bhagwan Jain Derasar',
    address: 'Indiranagar, Bangalore',
    location: { latitude: 12.9784, longitude: 77.6408 },
    sampradaya: 'shvetambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-blr-munisuvrat-ulsoor',
    name: 'Shri Munisuvrat Swami Jain Derasar',
    address: 'Ulsoor, Bangalore',
    location: { latitude: 12.9819, longitude: 77.6234 },
    sampradaya: 'shvetambar',
    rating: 4.5,
  },
  {
    placeId: 'seed-blr-mahavir-banaswadi',
    name: 'Shri Mahavir Jain Mandir',
    address: 'Banaswadi, Bangalore',
    location: { latitude: 13.0198, longitude: 77.6452 },
    sampradaya: 'digambar',
    rating: 4.5,
  },
  {
    placeId: 'seed-blr-chandraprabhu-rajajinagar',
    name: 'Shri Chandraprabhu Digambar Jain Mandir',
    address: 'Rajajinagar, Bangalore',
    location: { latitude: 12.9991, longitude: 77.5554 },
    sampradaya: 'digambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-blr-mahavir-whitefield',
    name: 'Shri Mahavir Swami Jain Mandir',
    address: 'Whitefield, Bangalore',
    location: { latitude: 12.9698, longitude: 77.7500 },
    sampradaya: 'shvetambar',
    rating: 4.5,
  },
  {
    placeId: 'seed-blr-adinath-hebbal',
    name: 'Shri Adinath Jain Mandir',
    address: 'Hebbal, Bangalore',
    location: { latitude: 13.0359, longitude: 77.5970 },
    sampradaya: 'digambar',
    rating: 4.5,
  },
  {
    placeId: 'seed-blr-mahavir-marathahalli',
    name: 'Shri Mahavir Jain Mandir',
    address: 'Marathahalli, Bangalore',
    location: { latitude: 12.9591, longitude: 77.6974 },
    sampradaya: 'shvetambar',
    rating: 4.5,
  },
  {
    placeId: 'seed-blr-mahavir-ecity',
    name: 'Shri 1008 Mahavira Digambar Jain Mandir',
    address: 'Electronic City, Bangalore',
    location: { latitude: 12.8456, longitude: 77.6603 },
    sampradaya: 'digambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-blr-sumatinath-koramangala',
    name: 'Shri Sumatinath Jain Derasar',
    address: 'Koramangala, Bangalore',
    location: { latitude: 12.9352, longitude: 77.6245 },
    sampradaya: 'shvetambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-blr-vimalnath-hsr',
    name: 'Shri Vimalnath Jain Mandir',
    address: 'HSR Layout, Bangalore',
    location: { latitude: 12.9116, longitude: 77.6473 },
    sampradaya: 'digambar',
    rating: 4.5,
  },
  {
    placeId: 'seed-blr-shantinath-btm',
    name: 'Shri Shantinath Jain Mandir',
    address: 'BTM Layout, Bangalore',
    location: { latitude: 12.9166, longitude: 77.6101 },
    sampradaya: 'digambar',
    rating: 4.5,
  },
  {
    placeId: 'seed-blr-adinath-yelahanka',
    name: 'Shri Adinath Jain Tirth',
    address: 'Yelahanka, Bangalore',
    location: { latitude: 13.1007, longitude: 77.5963 },
    sampradaya: 'shvetambar',
    rating: 4.5,
  },
  {
    placeId: 'seed-blr-mahavir-hennur',
    name: 'Shri Mahavir Jain Mandir',
    address: 'Hennur, Bangalore',
    location: { latitude: 13.0302, longitude: 77.6371 },
    sampradaya: 'digambar',
    rating: 4.4,
  },
  {
    placeId: 'seed-blr-parshwanath-cottonpet',
    name: 'Shri Parshwanath Jain Derasar',
    address: 'Cottonpet, Bangalore',
    location: { latitude: 12.9650, longitude: 77.5780 },
    sampradaya: 'shvetambar',
    rating: 4.5,
  },

  // ─── MAHARASHTRA ───────────────────────────────────────────
  {
    placeId: 'seed-mh-mangi-tungi',
    name: 'Mangi Tungi (Rishabhdev 108 ft)',
    address: 'Tahrabad, Nashik',
    location: { latitude: 20.7333, longitude: 74.0167 },
    sampradaya: 'digambar',
    rating: 4.8,
  },
  {
    placeId: 'seed-mh-kunthalgiri',
    name: 'Kunthalgiri Siddha Kshetra',
    address: 'Osmanabad',
    location: { latitude: 18.0833, longitude: 76.0833 },
    sampradaya: 'digambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-mh-gajpantha',
    name: 'Gajpantha Jain Tirth',
    address: 'Mhasrul, Nashik',
    location: { latitude: 19.9333, longitude: 73.8667 },
    sampradaya: 'digambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-mh-ellora',
    name: 'Ellora Jain Caves (Caves 30-34)',
    address: 'Ellora, Aurangabad',
    location: { latitude: 20.0258, longitude: 75.1796 },
    sampradaya: 'digambar',
    rating: 4.8,
  },
  {
    placeId: 'seed-mh-antariksh',
    name: 'Antariksh Parshwanath',
    address: 'Shirpur, Washim',
    location: { latitude: 21.3417, longitude: 75.1850 },
    sampradaya: 'digambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-mh-pune-camp',
    name: 'Shri Adinath Jain Mandir',
    address: 'Pune Camp',
    location: { latitude: 18.5167, longitude: 73.8782 },
    sampradaya: 'shvetambar',
    rating: 4.5,
  },

  // ─── TAMIL NADU ────────────────────────────────────────────
  {
    placeId: 'seed-tn-tirumalai',
    name: 'Tirumalai Jain Temple',
    address: 'Polur, Tiruvannamalai',
    location: { latitude: 12.6167, longitude: 78.9833 },
    sampradaya: 'digambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-tn-vallimalai',
    name: 'Vallimalai Jain Caves',
    address: 'Vellore',
    location: { latitude: 12.9333, longitude: 79.1333 },
    sampradaya: 'digambar',
    rating: 4.5,
  },
  {
    placeId: 'seed-tn-sittanavasal',
    name: 'Sittanavasal Jain Cave Temple',
    address: 'Pudukkottai',
    location: { latitude: 10.4500, longitude: 78.7167 },
    sampradaya: 'digambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-tn-chennai-mintst',
    name: 'Shri Chandraprabhu Jain Naya Mandir',
    address: 'Mint Street, Chennai',
    location: { latitude: 13.0950, longitude: 80.2820 },
    sampradaya: 'digambar',
    rating: 4.5,
  },

  // ─── BIHAR / JHARKHAND ─────────────────────────────────────
  {
    placeId: 'seed-jh-shikharji',
    name: 'Shri Sammed Shikharji (Parasnath)',
    address: 'Madhuban, Giridih',
    location: { latitude: 23.9667, longitude: 86.1333 },
    sampradaya: 'shvetambar',
    rating: 4.9,
  },
  {
    placeId: 'seed-bh-pawapuri',
    name: 'Pawapuri (Lord Mahavira Nirvana Sthal)',
    address: 'Pawapuri, Nalanda',
    location: { latitude: 25.0833, longitude: 85.5500 },
    sampradaya: 'shvetambar',
    rating: 4.8,
  },
  {
    placeId: 'seed-bh-vaishali',
    name: 'Vaishali (Lord Mahavira Birthplace)',
    address: 'Vaishali',
    location: { latitude: 25.6833, longitude: 85.1333 },
    sampradaya: 'shvetambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-bh-champapuri',
    name: 'Champapuri Jain Tirth',
    address: 'Bhagalpur',
    location: { latitude: 25.2500, longitude: 87.0167 },
    sampradaya: 'shvetambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-bh-rajgir',
    name: 'Rajgir Jain Temple',
    address: 'Rajgir, Nalanda',
    location: { latitude: 25.0333, longitude: 85.4167 },
    sampradaya: 'shvetambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-bh-lachuar',
    name: 'Lachuar Jain Tirth',
    address: 'Lachhuar, Jamui',
    location: { latitude: 24.9167, longitude: 86.2333 },
    sampradaya: 'shvetambar',
    rating: 4.5,
  },

  // ─── UTTAR PRADESH ─────────────────────────────────────────
  {
    placeId: 'seed-up-hastinapur',
    name: 'Hastinapur Jain Tirth',
    address: 'Hastinapur, Meerut',
    location: { latitude: 29.1583, longitude: 77.9889 },
    sampradaya: 'digambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-up-devagarh',
    name: 'Devagarh Jain Temples',
    address: 'Lalitpur',
    location: { latitude: 24.5167, longitude: 78.2333 },
    sampradaya: 'digambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-up-ayodhya',
    name: 'Ayodhya Digambar Jain Mandir',
    address: 'Ayodhya',
    location: { latitude: 26.7950, longitude: 82.1942 },
    sampradaya: 'digambar',
    rating: 4.6,
  },
  {
    placeId: 'seed-up-kampila',
    name: 'Kampilya Tirth',
    address: 'Kampila, Farrukhabad',
    location: { latitude: 27.6000, longitude: 79.2667 },
    sampradaya: 'digambar',
    rating: 4.5,
  },
  {
    placeId: 'seed-up-firozabad',
    name: 'Shri Chandraprabhu Digambar Jain Mandir',
    address: 'Firozabad',
    location: { latitude: 27.1500, longitude: 78.4000 },
    sampradaya: 'digambar',
    rating: 4.4,
  },

  // ─── ANDHRA / TELANGANA ────────────────────────────────────
  {
    placeId: 'seed-tl-kulpakji',
    name: 'Shri Kulpakji Jain Tirth',
    address: 'Kolanupaka, Yadadri Bhuvanagiri',
    location: { latitude: 17.6333, longitude: 78.9833 },
    sampradaya: 'shvetambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-tl-hyderabad-secunderabad',
    name: 'Shri Mahavir Jain Mandir',
    address: 'Secunderabad',
    location: { latitude: 17.4399, longitude: 78.4983 },
    sampradaya: 'shvetambar',
    rating: 4.5,
  },

  // ─── ORISSA ────────────────────────────────────────────────
  {
    placeId: 'seed-od-khandagiri',
    name: 'Khandagiri Jain Caves',
    address: 'Bhubaneswar',
    location: { latitude: 20.2620, longitude: 85.7842 },
    sampradaya: 'digambar',
    rating: 4.6,
  },

  // ─── HARYANA ───────────────────────────────────────────────
  {
    placeId: 'seed-hr-faridabad',
    name: 'Shri Adinath Digambar Jain Mandir',
    address: 'Faridabad',
    location: { latitude: 28.4089, longitude: 77.3178 },
    sampradaya: 'digambar',
    rating: 4.4,
  },
  {
    placeId: 'seed-hr-gurgaon',
    name: 'Shri Adinath Jain Shwetambar Mandir',
    address: 'Sector 14, Gurugram',
    location: { latitude: 28.4595, longitude: 77.0266 },
    sampradaya: 'shvetambar',
    rating: 4.5,
  },

  // ─── INTERNATIONAL ─────────────────────────────────────────
  {
    placeId: 'seed-intl-leicester',
    name: 'Jain Centre Leicester',
    address: 'Leicester, United Kingdom',
    location: { latitude: 52.6334, longitude: -1.1306 },
    sampradaya: 'shvetambar',
    rating: 4.8,
  },
  {
    placeId: 'seed-intl-potters-bar',
    name: 'Oshwal Jain Centre',
    address: 'Potters Bar, London',
    location: { latitude: 51.6896, longitude: -0.1707 },
    sampradaya: 'shvetambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-intl-boston',
    name: 'Jain Center of Greater Boston',
    address: 'Norwood, Massachusetts, USA',
    location: { latitude: 42.1948, longitude: -71.1992 },
    sampradaya: 'shvetambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-intl-jcnj',
    name: 'Jain Center of New Jersey',
    address: 'Franklin Township, NJ, USA',
    location: { latitude: 40.5187, longitude: -74.4068 },
    sampradaya: 'shvetambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-intl-jcnc',
    name: 'Jain Center of Northern California',
    address: 'Milpitas, CA, USA',
    location: { latitude: 37.4296, longitude: -121.8964 },
    sampradaya: 'shvetambar',
    rating: 4.8,
  },
  {
    placeId: 'seed-intl-toronto',
    name: 'Jain Society of Toronto',
    address: 'Etobicoke, Toronto, Canada',
    location: { latitude: 43.7000, longitude: -79.5500 },
    sampradaya: 'shvetambar',
    rating: 4.7,
  },
  {
    placeId: 'seed-intl-nairobi',
    name: 'Visa Oshwal Community Centre',
    address: 'Nairobi, Kenya',
    location: { latitude: -1.2728, longitude: 36.8055 },
    sampradaya: 'shvetambar',
    rating: 4.7,
  },
];
